# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PokerWebSocketTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PokerWebSocketTest
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!

pod 'Starscream', '~> 3.0.2'
  target 'PokerWebSocketTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokerWebSocketTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
